### ISSUE TITLE
要一次性签到多个账号或者网站怎么弄呢？

### ISSUE THREAD

**Issue by hzys** [isecret/sspanel-autocheckin#10]
我只知道最死板的办法是改yml 多复制几个- name: Request API，然后多设置几个Secrets，请问要用if语句循环的话该怎么写呢？类似https://github.com/t00t00-crypto/wyy-action/blob/master/.github/workflows/run.yml 这种

**Comment by isecret** [comment]
我给你提供一个思路哈，你可以尝试这样。
给个新的 `Secret`：`Config`：
```json
[
    {
        "domain": "https://aaa.com",
        "username": "username1",
        "password": "password1"
    },
   {
        "domain": "https://bbb.com",
        "username": "username2",
        "password": "password2"
    },
   {
        "domain": "https://ccc.com",
        "username": "username3",
        "password": "password3"
    },
]
```
然后脚本需要配置，读取这个 Json 解析这个数组然后遍历，当然，这个用 JS 写比较方便，Shell 对 Json 支持并不是很友好。

**Comment by ella1314** [comment]
请问这个是哪个运行商的签到啊，移动，还是电信，域名值填写什么？

**Comment by isecret** [comment]
> 请问这个是哪个运行商的签到啊，移动，还是电信，域名值填写什么？

这个是给机场签到的，只要是基于 [SSPanel-Uim](https://github.com/Anankke/SSPanel-Uim) 搭建的客户端面板都能签到，除非机场主加了签到验证码。

**Comment by ella1314** [comment]
> > 请问这个是哪个运行商的签到啊，移动，还是电信，域名值填写什么？
> 
> 这个是给机场签到的，只要是基于 [SSPanel-Uim](https://github.com/Anankke/SSPanel-Uim) 搭建的客户端面板都能签到，除非机场主加了签到验证码。

了解了，谢谢，DOMAIN对应的secret值是不是机场订阅的网址？

**Comment by isecret** [comment]
> > > 请问这个是哪个运行商的签到啊，移动，还是电信，域名值填写什么？
> > 
> > 
> > 这个是给机场签到的，只要是基于 [SSPanel-Uim](https://github.com/Anankke/SSPanel-Uim) 搭建的客户端面板都能签到，除非机场主加了签到验证码。
> 
> 了解了，谢谢，DOMAIN对应的secret值是不是机场订阅的网址？

对的，填写完成后你可以点击自己仓库的 star 来触发，观察输出会不会有异常，没有异常的话明天早上 2:20 会自动执行。

**Comment by isecret** [comment]
> > > > 请问这个是哪个运行商的签到啊，移动，还是电信，域名值填写什么？
> > > 
> > > 
> > > 这个是给机场签到的，只要是基于 [SSPanel-Uim](https://github.com/Anankke/SSPanel-Uim) 搭建的客户端面板都能签到，除非机场主加了签到验证码。
> > 
> > 
> > 了解了，谢谢，DOMAIN对应的secret值是不是机场订阅的网址？
> 
> 对的，填写完成后你可以点击自己仓库的 star 来触发，观察输出会不会有异常，没有异常的话明天早上 2:20 会自动执行。

修正一下，不是订阅地址，就是域名，也就是你进入个人管理页面的域名。

**Comment by ella1314** [comment]
> star

star后提示签到成功，谢谢。

**Comment by Ryanjiena** [comment]
https://github.com/isecret/sspanel-autocheckin/blob/7fc4c7c851971a67e89439f03f35110856e6fbc3/.github/workflows/work.yaml#L13-L18

**Comment by isecret** [comment]
v2.0 版本已实现多站点多用户。
