### ISSUE TITLE
任务执行失败

### ISSUE THREAD

**Issue by lukemin** [isecret/sspanel-autocheckin#11]
Run sudo apt-get update
Hit:1 http://azure.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://azure.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:4 http://dl.google.com/linux/chrome/deb stable InRelease [1811 B]
Get:5 http://packages.cloud.google.com/apt cloud-sdk InRelease [6349 B]
Hit:6 https://storage.googleapis.com/bazel-apt stable InRelease
Hit:7 https://download.mono-project.com/repo/ubuntu stable-bionic InRelease
Get:8 https://packages.microsoft.com/repos/azure-cli bionic InRelease [3965 B]
Get:9 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease [4002 B]
Hit:10 https://dl.yarnpkg.com/debian stable InRelease
Ign:12 https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 InRelease
Get:13 https://cli-assets.heroku.com/apt ./ InRelease [2879 B]
Hit:14 https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 Release
Get:15 http://ppa.launchpad.net/ansible/ansible/ubuntu bionic InRelease [15.9 kB]
Get:16 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:11 https://packages.cloud.google.com/apt kubernetes-xenial InRelease [8993 B]
Err:17 https://packagecloud.io/github/git-lfs/ubuntu bionic InRelease
  402  Payment Required [IP: 54.183.38.243 443]
Get:18 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease [103 kB]
Get:19 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  InRelease [1613 B]
Hit:20 http://ppa.launchpad.net/apt-fast/stable/ubuntu bionic InRelease
Get:21 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1727 kB]
Ign:22 https://dl.bintray.com/sbt/debian  InRelease
Get:23 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [367 kB]
Get:24 http://azure.archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [184 kB]
Get:25 http://azure.archive.ubuntu.com/ubuntu bionic-updates/restricted Translation-en [24.6 kB]
Get:26 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1683 kB]
Get:27 https://dl.bintray.com/sbt/debian  Release [815 B]
Get:28 http://ppa.launchpad.net/git-core/ppa/ubuntu bionic InRelease [20.8 kB]
Get:29 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [354 kB]
Get:30 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1089 B]
Get:31 http://ppa.launchpad.net/hvr/ghc/ubuntu bionic InRelease [15.3 kB]
Get:32 http://packages.cloud.google.com/apt cloud-sdk/main amd64 Packages [144 kB]
Get:33 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease [20.8 kB]
Hit:34 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic InRelease
Get:35 https://packages.microsoft.com/repos/azure-cli bionic/main amd64 Packages [11.2 kB]
Get:36 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages [142 kB]
Get:37 https://cli-assets.heroku.com/apt ./ Packages [620 B]
Get:39 http://ppa.launchpad.net/ansible/ansible/ubuntu bionic/main amd64 Packages [820 B]
Get:40 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1400 kB]
Get:41 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  Packages [6389 B]
Get:43 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [277 kB]
Get:44 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [166 kB]
Get:45 http://security.ubuntu.com/ubuntu bionic-security/restricted Translation-en [22.1 kB]
Get:46 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1079 kB]
Get:47 http://security.ubuntu.com/ubuntu bionic-security/universe Translation-en [241 kB]
Get:48 http://ppa.launchpad.net/git-core/ppa/ubuntu bionic/main amd64 Packages [3048 B]
Get:49 http://apt.postgresql.org/pub/repos/apt bionic-pgdg/main amd64 Packages [229 kB]
Get:50 http://ppa.launchpad.net/hvr/ghc/ubuntu bionic/main amd64 Packages [11.6 kB]
Get:51 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages [80.3 kB]
Reading package lists...
E: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/bionic/InRelease  402  Payment Required [IP: 54.183.38.243 443]
E: The repository 'https://packagecloud.io/github/git-lfs/ubuntu bionic InRelease' is no longer signed.
Error: Process completed with exit code 100.

**Comment by isecret** [comment]
看上去依赖的远程仓库出了一些问题，等晚点再试试吧。

**Comment by lukemin** [comment]
已恢复正常。
