### ISSUE TITLE
新建了 secret，结果 actions 执行结果还是报错了

### ISSUE THREAD

**Issue by shaonwu** [isecret/sspanel-autocheckin#13]
报错信息如下：

Request API
 bash ssp-autocheckin.sh
  shell: /bin/bash -e {0}
  env:
    TZ: Asia/Shanghai
    DOMAIN: 
    USERNAME: 
    PASSWD: 
    PUSH_KEY: 
环境常量未配置，请正确配置 DOMAIN、USERNAME 和 PASSWD 值
Error: Process completed with exit code 1.

**Comment by shaonwu** [comment]
新建了 secret，结果 actions 执行结果还是报错了，如下：

Request API
 bash ssp-autocheckin.sh
  shell: /bin/bash -e {0}
  env:
    TZ: Asia/Shanghai
    DOMAIN: 
    USERNAME: 
    PASSWD: 
    PUSH_KEY: 
环境常量未配置，请正确配置 DOMAIN、USERNAME 和 PASSWD 值
Error: Process completed with exit code 1.

**Comment by isecret** [comment]
看样子 ENV 没有传递进去，删掉重新创建 Secret 试试。

**Comment by shaonwu** [comment]
> 看样子 ENV 没有传递进去，删掉重新创建 Secret 试试。

好的，感谢解答，我先试试。

**Comment by shaonwu** [comment]
> 看样子 ENV 没有传递进去，删掉重新创建 Secret 试试。

还是不行，同样的报错信息

**Comment by isecret** [comment]
> > 看样子 ENV 没有传递进去，删掉重新创建 Secret 试试。
> 
> 还是不行，同样的报错信息

这个很奇怪哦，还没遇到过这种问题。确定 Sercret 的值是正确的吗？

**Comment by shaonwu** [comment]
> > > 看样子 ENV 没有传递进去，删掉重新创建 Secret 试试。
> > 
> > 
> > 还是不行，同样的报错信息
> 
> 这个很奇怪哦，还没遇到过这种问题。确定 Sercret 的值是正确的吗？

值是正确的，会不会是网站域名的问题？有时候没办法稳定直连

**Comment by isecret** [comment]
> > > > 看样子 ENV 没有传递进去，删掉重新创建 Secret 试试。
> > > 
> > > 
> > > 还是不行，同样的报错信息
> > 
> > 
> > 这个很奇怪哦，还没遇到过这种问题。确定 Sercret 的值是正确的吗？
> 
> 值是正确的，会不会是网站域名的问题？有时候没办法稳定直连

不会吧，这里的异常是填写的值（域名、用户名、密码）有为空的才会抛出，你在自己的服务器上试试呢？

**Comment by shaonwu** [comment]
> > > > > 看样子 ENV 没有传递进去，删掉重新创建 Secret 试试。
> > > > 
> > > > 
> > > > 还是不行，同样的报错信息
> > > 
> > > 
> > > 这个很奇怪哦，还没遇到过这种问题。确定 Sercret 的值是正确的吗？
> > 
> > 
> > 值是正确的，会不会是网站域名的问题？有时候没办法稳定直连
> 
> 不会吧，这里的异常是填写的值（域名、用户名、密码）有为空的才会抛出，你在自己的服务器上试试呢？

Secret 的内容我是直接按照这个格式填写的，引号里面的内容替换成对应的内容了

DOMAIN="https://****.best" # 域名
USERNAME="EMAIL" # 登录名
PASSWD="PASSWORD" # 密码
PUSH_KEY="PUSH_KEY" # Server 酱推送 SCKEY，非必填

**Comment by shaonwu** [comment]
> > > > > 看样子 ENV 没有传递进去，删掉重新创建 Secret 试试。
> > > > 
> > > > 
> > > > 还是不行，同样的报错信息
> > > 
> > > 
> > > 这个很奇怪哦，还没遇到过这种问题。确定 Sercret 的值是正确的吗？
> > 
> > 
> > 值是正确的，会不会是网站域名的问题？有时候没办法稳定直连
> 
> 不会吧，这里的异常是填写的值（域名、用户名、密码）有为空的才会抛出，你在自己的服务器上试试呢？

我找个服务器试一下吧

**Comment by isecret** [comment]
> > > > > > 看样子 ENV 没有传递进去，删掉重新创建 Secret 试试。
> > > > > 
> > > > > 
> > > > > 还是不行，同样的报错信息
> > > > 
> > > > 
> > > > 这个很奇怪哦，还没遇到过这种问题。确定 Sercret 的值是正确的吗？
> > > 
> > > 
> > > 值是正确的，会不会是网站域名的问题？有时候没办法稳定直连
> > 
> > 
> > 不会吧，这里的异常是填写的值（域名、用户名、密码）有为空的才会抛出，你在自己的服务器上试试呢？
> 
> Secret 的内容我是直接按照这个格式填写的，引号里面的内容替换成对应的内容了
> 
> DOMAIN="https://****.best" # 域名
> USERNAME="EMAIL" # 登录名
> PASSWD="PASSWORD" # 密码
> PUSH_KEY="PUSH_KEY" # Server 酱推送 SCKEY，非必填

尝试删除注释试试？

**Comment by isecret** [comment]
> > > > > > > 看样子 ENV 没有传递进去，删掉重新创建 Secret 试试。
> > > > > > 
> > > > > > 
> > > > > > 还是不行，同样的报错信息
> > > > > 
> > > > > 
> > > > > 这个很奇怪哦，还没遇到过这种问题。确定 Sercret 的值是正确的吗？
> > > > 
> > > > 
> > > > 值是正确的，会不会是网站域名的问题？有时候没办法稳定直连
> > > 
> > > 
> > > 不会吧，这里的异常是填写的值（域名、用户名、密码）有为空的才会抛出，你在自己的服务器上试试呢？
> > 
> > 
> > Secret 的内容我是直接按照这个格式填写的，引号里面的内容替换成对应的内容了
> > DOMAIN="https://****.best" # 域名
> > USERNAME="EMAIL" # 登录名
> > PASSWD="PASSWORD" # 密码
> > PUSH_KEY="PUSH_KEY" # Server 酱推送 SCKEY，非必填
> 
> 尝试删除注释试试？

不对，你是用 Actions 的话，对应 Secert 分别键为 `DOMAIN`，值填入 域名；`USERNAME` 键，值填写你的登录用户名，值不是直接复制 `DOMAIN="https://****.best" # 域名` 的哦。

**Comment by shaonwu** [comment]
> > > > > > > > 看样子 ENV 没有传递进去，删掉重新创建 Secret 试试。
> > > > > > > 
> > > > > > > 
> > > > > > > 还是不行，同样的报错信息
> > > > > > 
> > > > > > 
> > > > > > 这个很奇怪哦，还没遇到过这种问题。确定 Sercret 的值是正确的吗？
> > > > > 
> > > > > 
> > > > > 值是正确的，会不会是网站域名的问题？有时候没办法稳定直连
> > > > 
> > > > 
> > > > 不会吧，这里的异常是填写的值（域名、用户名、密码）有为空的才会抛出，你在自己的服务器上试试呢？
> > > 
> > > 
> > > Secret 的内容我是直接按照这个格式填写的，引号里面的内容替换成对应的内容了
> > > DOMAIN="https://****.best" # 域名
> > > USERNAME="EMAIL" # 登录名
> > > PASSWD="PASSWORD" # 密码
> > > PUSH_KEY="PUSH_KEY" # Server 酱推送 SCKEY，非必填
> > 
> > 
> > 尝试删除注释试试？
> 
> 不对，你是用 Actions 的话，对应 Secert 分别键为 `DOMAIN`，值填入 域名；`USERNAME` 键，值填写你的登录用户名，值不是直接复制 `DOMAIN="https://****.best" # 域名` 的哦。

那我再多试试，谢谢

**Comment by shaonwu** [comment]
> > > > > > > > 看样子 ENV 没有传递进去，删掉重新创建 Secret 试试。
> > > > > > > 
> > > > > > > 
> > > > > > > 还是不行，同样的报错信息
> > > > > > 
> > > > > > 
> > > > > > 这个很奇怪哦，还没遇到过这种问题。确定 Sercret 的值是正确的吗？
> > > > > 
> > > > > 
> > > > > 值是正确的，会不会是网站域名的问题？有时候没办法稳定直连
> > > > 
> > > > 
> > > > 不会吧，这里的异常是填写的值（域名、用户名、密码）有为空的才会抛出，你在自己的服务器上试试呢？
> > > 
> > > 
> > > Secret 的内容我是直接按照这个格式填写的，引号里面的内容替换成对应的内容了
> > > DOMAIN="https://****.best" # 域名
> > > USERNAME="EMAIL" # 登录名
> > > PASSWD="PASSWORD" # 密码
> > > PUSH_KEY="PUSH_KEY" # Server 酱推送 SCKEY，非必填
> > 
> > 
> > 尝试删除注释试试？
> 
> 不对，你是用 Actions 的话，对应 Secert 分别键为 `DOMAIN`，值填入 域名；`USERNAME` 键，值填写你的登录用户名，值不是直接复制 `DOMAIN="https://****.best" # 域名` 的哦。

重新看了一下文档，发现自己理解错意思了，实在不好意思，浪费这么时间。感谢解答，现在运行正常了，登录失败和签到失败应该是网址或者字符的问题了，我自己排查一下，再次感谢。

**Comment by shaonwu** [comment]
> > > > > > > > 看样子 ENV 没有传递进去，删掉重新创建 Secret 试试。
> > > > > > > 
> > > > > > > 
> > > > > > > 还是不行，同样的报错信息
> > > > > > 
> > > > > > 
> > > > > > 这个很奇怪哦，还没遇到过这种问题。确定 Sercret 的值是正确的吗？
> > > > > 
> > > > > 
> > > > > 值是正确的，会不会是网站域名的问题？有时候没办法稳定直连
> > > > 
> > > > 
> > > > 不会吧，这里的异常是填写的值（域名、用户名、密码）有为空的才会抛出，你在自己的服务器上试试呢？
> > > 
> > > 
> > > Secret 的内容我是直接按照这个格式填写的，引号里面的内容替换成对应的内容了
> > > DOMAIN="https://****.best" # 域名
> > > USERNAME="EMAIL" # 登录名
> > > PASSWD="PASSWORD" # 密码
> > > PUSH_KEY="PUSH_KEY" # Server 酱推送 SCKEY，非必填
> > 
> > 
> > 尝试删除注释试试？
> 
> 不对，你是用 Actions 的话，对应 Secert 分别键为 `DOMAIN`，值填入 域名；`USERNAME` 键，值填写你的登录用户名，值不是直接复制 `DOMAIN="https://****.best" # 域名` 的哦。

这么报错的话，应该是域名、账号或者密码的问题了吧？

parse error: Invalid numeric literal at line 1, column 7
[2020-12-28 17:41:08] "登录失败"
parse error: Invalid numeric literal at line 1, column 7
[2020-12-28 17:41:08] "签到失败"
[2020-12-28 17:41:08] "签到结果推送成功"

**Comment by isecret** [comment]
如果可以，能提供一下你 `DOMAIN` 填写的域名吗？感觉你的值填写的不太对。

**Comment by isecret** [comment]
> > > > > > > > > 看样子 ENV 没有传递进去，删掉重新创建 Secret 试试。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 还是不行，同样的报错信息
> > > > > > > 
> > > > > > > 
> > > > > > > 这个很奇怪哦，还没遇到过这种问题。确定 Sercret 的值是正确的吗？
> > > > > > 
> > > > > > 
> > > > > > 值是正确的，会不会是网站域名的问题？有时候没办法稳定直连
> > > > > 
> > > > > 
> > > > > 不会吧，这里的异常是填写的值（域名、用户名、密码）有为空的才会抛出，你在自己的服务器上试试呢？
> > > > 
> > > > 
> > > > Secret 的内容我是直接按照这个格式填写的，引号里面的内容替换成对应的内容了
> > > > DOMAIN="https://****.best" # 域名
> > > > USERNAME="EMAIL" # 登录名
> > > > PASSWD="PASSWORD" # 密码
> > > > PUSH_KEY="PUSH_KEY" # Server 酱推送 SCKEY，非必填
> > > 
> > > 
> > > 尝试删除注释试试？
> > 
> > 
> > 不对，你是用 Actions 的话，对应 Secert 分别键为 `DOMAIN`，值填入 域名；`USERNAME` 键，值填写你的登录用户名，值不是直接复制 `DOMAIN="https://****.best" # 域名` 的哦。
> 
> 这么报错的话，应该是域名、账号或者密码的问题了吧？
> 
> parse error: Invalid numeric literal at line 1, column 7
> [2020-12-28 17:41:08] "登录失败"
> parse error: Invalid numeric literal at line 1, column 7
> [2020-12-28 17:41:08] "签到失败"
> [2020-12-28 17:41:08] "签到结果推送成功"

或者说提供一个你填写的格式，值的话你可以手动混淆一下。

**Comment by shaonwu** [comment]
> 如果可以，能提供一下你 `DOMAIN` 填写的域名吗？感觉你的值填写的不太对。

DOMAIN 域名的值 https://getfree.cloud

**Comment by isecret** [comment]
看上去是 SSPanel 程序，或者等我晚点更新一个版本再试试吧，重写了一些地方。

**Comment by shaonwu** [comment]
> 看上去是 SSPanel 程序，或者等我晚点更新一个版本再试试吧，重写了一些地方。

好，谢谢。

**Comment by isecret** [comment]
重写 Fork 仓库或者合并更新试试，记得看文档，这个版本和之前的配置不兼容。

**Comment by shaonwu** [comment]
> 重写 Fork 仓库或者合并更新试试，记得看文档，这个版本和之前的配置不兼容。

我把本来的 repo 删除了重新 fork 了，新建了一个多用户签到的任务，第一个任务成功了，本来出错的那个网站，还是一样的报错，估计是网站的问题，我明天登录网站手动签到看看有没有签到验证码吧，谢谢了。

---------------------------------------

parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
ssp-autocheckin.sh: line 47: [: -eq: unary operator expected
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
【签到站点】: https://getfree.cloud

【签到用户】: xxxxxxxx@oxxxxxk.com

【签到时间】: 2020-12-28 19:53:12

【签到状态】: 签到失败, 请检查是否存在签到验证码

【用户余额】: CNY

【用户限速】: Mbps

【总流量】: 0 GB

【剩余流量】: 0 GB

【已使用流量】: 0 GB

【等级过期时间】: 

【账户过期时间】: 

【上次签到时间】: 1970-01-01 08:00:01


【推送结果】: 成功

---------------------------------------

**Comment by isecret** [comment]
> 我把本来的 repo 删除了重新 fork 了，新建了一个多用户签到的任务，第一个任务成功了，本来出错的那个网站，还是一样的报错，估计是网站的问题，我明天登录网站手动签到看看有没有签到验证码吧，谢谢了。

再重写 fork 仓库，刚刚重新调整了登录的逻辑。

**Comment by shaonwu** [comment]
> > 我把本来的 repo 删除了重新 fork 了，新建了一个多用户签到的任务，第一个任务成功了，本来出错的那个网站，还是一样的报错，估计是网站的问题，我明天登录网站手动签到看看有没有签到验证码吧，谢谢了。
> 
> 再重写 fork 仓库，刚刚重新调整了登录的逻辑。

---------------------------------------

重写 fork 仓库，报错信息和提示信息跟刚才不太一样

parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
ssp-autocheckin.sh: line 47: [: ==: unary operator expected
【签到站点】: https://getfree.cloud

【签到用户】: xxxxxxxxx@oxxxxxk.com

【签到时间】: 2020-12-28 20:06:45

【签到状态】: 登录失败, 请检查配置


【推送结果】: 成功

---------------------------------------

**Comment by Ryanjiena** [comment]
> > 如果可以，能提供一下你 `DOMAIN` 填写的域名吗？感觉你的值填写的不太对。
> 
> DOMAIN 域名的值 https://getfree.cloud

这个站支持 TGBot 签到……

**Comment by shaonwu** [comment]
> > > 如果可以，能提供一下你 `DOMAIN` 填写的域名吗？感觉你的值填写的不太对。
> > 
> > 
> > DOMAIN 域名的值 https://getfree.cloud
> 
> 这个站支持 TGBot 签到……

对，我刚去去网页看了一眼，网站上居然没有签到的按钮...之前我都是在 TGbot 上签到。这是不是意味着，这个脚本根本没办法起作用啊...

**Comment by Ryanjiena** [comment]
> > > > 如果可以，能提供一下你 `DOMAIN` 填写的域名吗？感觉你的值填写的不太对。
> > > 
> > > 
> > > DOMAIN 域名的值 https://getfree.cloud
> > 
> > 
> > 这个站支持 TGBot 签到……
> 
> 对，我刚去去网页看了一眼，网站上居然没有签到的按钮...之前我都是在 TGbot 上签到。这是不是意味着，这个脚本根本没办法起作用啊...

yes 😂

**Comment by shaonwu** [comment]
> > > > > 如果可以，能提供一下你 `DOMAIN` 填写的域名吗？感觉你的值填写的不太对。
> > > > 
> > > > 
> > > > DOMAIN 域名的值 https://getfree.cloud
> > > 
> > > 
> > > 这个站支持 TGBot 签到……
> > 
> > 
> > 对，我刚去去网页看了一眼，网站上居然没有签到的按钮...之前我都是在 TGbot 上签到。这是不是意味着，这个脚本根本没办法起作用啊...
> 
> yes 😂

我要是早点去网站上看一下就不会浪费你这么时间了，实在不好意思😂

**Comment by shaonwu** [comment]
> > > > > 如果可以，能提供一下你 `DOMAIN` 填写的域名吗？感觉你的值填写的不太对。
> > > > 
> > > > 
> > > > DOMAIN 域名的值 https://getfree.cloud
> > > 
> > > 
> > > 这个站支持 TGBot 签到……
> > 
> > 
> > 对，我刚去去网页看了一眼，网站上居然没有签到的按钮...之前我都是在 TGbot 上签到。这是不是意味着，这个脚本根本没办法起作用啊...
> 
> yes 😂

本来是觉得每天要上 TG 签到太麻烦了，想找个脚本自动签到，没想到最后还是回到原点😂

**Comment by Ryanjiena** [comment]
> > > > > > 如果可以，能提供一下你 `DOMAIN` 填写的域名吗？感觉你的值填写的不太对。
> > > > > 
> > > > > 
> > > > > DOMAIN 域名的值 https://getfree.cloud
> > > > 
> > > > 
> > > > 这个站支持 TGBot 签到……
> > > 
> > > 
> > > 对，我刚去去网页看了一眼，网站上居然没有签到的按钮...之前我都是在 TGbot 上签到。这是不是意味着，这个脚本根本没办法起作用啊...
> > 
> > 
> > yes 😂
> 
> 本来是觉得每天要上 TG 签到太麻烦了，想找个脚本自动签到，没想到最后还是回到原点😂

刚才看了一下这个站 3 天签到 1 次就行，而且每次签到都送 15G+ 流量，都用不完……

**Comment by shaonwu** [comment]
> > > > > > > 如果可以，能提供一下你 `DOMAIN` 填写的域名吗？感觉你的值填写的不太对。
> > > > > > 
> > > > > > 
> > > > > > DOMAIN 域名的值 https://getfree.cloud
> > > > > 
> > > > > 
> > > > > 这个站支持 TGBot 签到……
> > > > 
> > > > 
> > > > 对，我刚去去网页看了一眼，网站上居然没有签到的按钮...之前我都是在 TGbot 上签到。这是不是意味着，这个脚本根本没办法起作用啊...
> > > 
> > > 
> > > yes 😂
> > 
> > 
> > 本来是觉得每天要上 TG 签到太麻烦了，想找个脚本自动签到，没想到最后还是回到原点😂
> 
> 刚才看了一下这个站 3 天签到 1 次就行，而且每次签到都送 15G+ 流量，都用不完……

好像是2-3天，不太确定，但是断签一次就全部清空了...我用这个脚本可以签到另一个站点，很好用，谢谢你了。这个只支持 TGbot 签到的案例是不是也可以加进脚本签到失败的提示信息里面了😂
