### ISSUE TITLE
签到站点增加 Cloudflare DDoS Protection 导致账号登录失败

### ISSUE THREAD

**Issue by shaonwu** [isecret/sspanel-autocheckin#24]
今早推送信息显示登录失败，查看 Actions 报错信息如下：

Run bash ssp-autocheckin.sh
  bash ssp-autocheckin.sh
  shell: /bin/bash -e {0}
  env:
    TZ: Asia/Shanghai
    USERS: ***
    PUSH_KEY: ***
parse error: Invalid numeric literal at line 1, column 10
parse error: Invalid numeric literal at line 1, column 10
ssp-autocheckin.sh: line 47: [: ==: unary operator expected
【签到站点】: https://******.cloud

【签到用户】: *********@o*****k.com

【签到时间】: 2020-12-30 03:04:19

【签到状态】: 登录失败, 请检查配置

【推送结果】: 成功

---------------------------------------

登录网站查看，发现站点增加了 Cloudflare DDoS Protection，应该是是这个原因导致登录失败的，这个不知能否解决，谢谢。

**Comment by isecret** [comment]
这个就很麻烦了哦，暂时不考虑开启防护的站点。

**Comment by isecret** [comment]
或者等一段时间吧，最近知名点的都在被 D，应该是临时开启防护。

**Comment by shaonwu** [comment]
> 或者等一段时间吧，最近知名点的都在被 D，应该是临时开启防护。

好的，那我先把 Secret 删了。
