### ISSUE TITLE
请问消息通知是否可以增加推送至钉钉

### ISSUE THREAD

**Issue by yikZero** [isecret/sspanel-autocheckin#33]
钉钉 添加 自定义机器人 文档：[https://developers.dingtalk.com/document/app/custom-robot-access](https://developers.dingtalk.com/document/app/custom-robot-access)

非常感谢开发者。

**Comment by isecret** [comment]
Hello，我这边做了一个支持钉钉机器人通知对版本，目前在 `feat/33` 分支，由于没有使用钉钉，如果可以对话请帮忙测试一下。

**Comment by yikZero** [comment]
你好呀，我这边试了下，我的钉钉机器人没有设置加签，同时也确定钉钉`access_token`没有错误。推送失败了~

ps:在`feat/33`的 `work.yaml` 的`env`中并没有传入`DDBOT_TOKEN` ,我自行添加了：`DDBOT_TOKEN: ${{secrets.DDBOT_TOKEN}}`

![image](https://user-images.githubusercontent.com/52102693/111758760-d18da800-88d7-11eb-9ee7-10f164c51adb.png)

**Comment by yikZero** [comment]
另外，我自己常用的机场一直都登录不上，我换了个机场注册了个账号才登陆测试的。
我常用的机场邮箱：zyjXXXX99@gmail.com 密码包含 `$` `&`  不知道有没有影响 没有二步验证，也没有验证码

![image](https://user-images.githubusercontent.com/52102693/111759648-c8510b00-88d8-11eb-8c59-0569b7e42896.png)

**Comment by isecret** [comment]
那这个可能就是 Bug 了，另外能添加我对 tg 协助我测试一下钉钉嘛？tgId: `iiisecret`
