### ISSUE TITLE
请问用户名不是邮箱要怎么登陆

### ISSUE THREAD

**Issue by Xuziyin** [isecret/sspanel-autocheckin#35]
比如我的用户是aaaaaaaaaa
登录会报错，用户名变成
aa⁎⁎⁎@aa⁎⁎⁎.aaaaaaaaaa

**Comment by isecret** [comment]
emmm...目前只考虑到了邮箱用户名的情况，能给个测试站点吗？我注册个账号做适配。

**Comment by Xuziyin** [comment]
http://j01.space/
感谢大佬

**Comment by isecret** [comment]
改平台并非 SSPanel 系统，接口与 SSPanel 不同。

**Comment by Xuziyin** [comment]
感谢大佬
