### ISSUE TITLE
https://ikuuu.co之前可以，突然不能签到了

### ISSUE THREAD

**Issue by zichouyin** [isecret/sspanel-autocheckin#38]
【签到状态】: 登录失败, 请检查配置
大概两天前不能，配置USERS,按照说明来的

**Comment by zichouyin** [comment]
之前可以的，大概两天前突然不行了

**Comment by wudongdefeng** [comment]
ikuuu增加了登录验证，所以失效了


Starting new HTTPS connection (1): ikuuu.co:443

https://ikuuu.co:443 "POST /auth/login HTTP/1.1" 200 None

登陆失败

https://ikuuu.co:443 "POST /auth/send HTTP/1.1" 200 None

{"ret":0,"msg":"\u6b64\u90ae\u7bb1\u5df2\u7ecf\u6ce8\u518c"}

0

**Comment by isecret** [comment]
看到登录页有验证码，暂不支持验证码哦。

**Comment by isecret** [comment]
倒是后续支持了 Cookie 签到可以试试。

**Comment by zichouyin** [comment]
谢谢
