### ISSUE TITLE
多网站登陆失败

### ISSUE THREAD

**Issue by a327777892** [isecret/sspanel-autocheckin#42]
用户 1

【签到站点】: https://⁎⁎⁎.xyz
【签到用户】: 32⁎⁎⁎@qq⁎⁎⁎.com
【签到时间】: 2021-03-29 00:22:44
【签到状态】: 登录失败, 请检查配置
用户 2

【签到站点】: https://⁎⁎⁎.co
【签到用户】: 32⁎⁎⁎@qq⁎⁎⁎.com
【签到时间】: 2021-03-29 00:22:44
【签到状态】: 登录失败, 请检查配置

单账号没问题，多账号就出错，我格式估计错了，麻烦给个人多网站 账号配置的模版 谢谢

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by isecret** [comment]
Hello，我这边测试过了多账号配置是没问题的，格式如下：

编辑 `.env`：
```
USERS="https://abc.com----a@abc.com---abc123456;
https://xyz.com----x@xyz.com---xyz123456;
"
```

或 Github Actions 设置 *Secret* 名为 `USERS` 值如下:
```
https://abc.com----a@abc.com---abc123456;
https://xyz.com----x@xyz.com---xyz123456;
```
