### ISSUE TITLE
配置了 Secret DISPLAY_CONTEXT 的值为 0以后，依旧推送了完整的信息。

### ISSUE THREAD

**Issue by udeve** [isecret/sspanel-autocheckin#45]
配置了 Secret DISPLAY_CONTEXT 的值为 0以后，依旧推送了完整的信息。
0.![批注 配置了 Secret DISPLAY_CONTEXT 的值为 0](https://user-images.githubusercontent.com/32419091/114275229-5477cd80-9a54-11eb-9044-707deb4c12ef.jpg)

1.![批注 依旧返回了完整的信息](https://user-images.githubusercontent.com/32419091/114275242-5f326280-9a54-11eb-9868-eab83b5ed287.jpg)

**Comment by isecret** [comment]
你理解错了 `DISPLAY_CONTEXT` 参数的含义了，这个参数是用于执行任务时不输出日志内容，主要用于隐私保护。如果你想禁用内容推送可以删除相关推送渠道的密钥。
