### ISSUE TITLE
一个比较严重的问题

### ISSUE THREAD

**Issue by jing5460** [isecret/sspanel-autocheckin#47]
机场在官网或者电报组里 签到每次都会有10G 以上的流量，但是用到本项目Actions 签到 每次只有30M 左右的流量  ，这是什么原因？
这是电报组 签到截图
![image](https://user-images.githubusercontent.com/38358681/115917027-31173e80-a4a8-11eb-916b-0f66e8075ee0.png)
这是本项目 签到截图
![image](https://user-images.githubusercontent.com/38358681/115917186-6ae84500-a4a8-11eb-82a5-5805da459969.png)

**Comment by isecret** [comment]
脚本的本质是模拟官网签到，你试试在官网签到和电报群带奖励是一样吗？可能渠道不同给的奖励不一样？
