### ISSUE TITLE
签到失败问题

### ISSUE THREAD

**Issue by nikaidou721** [isecret/sspanel-autocheckin#5]
[2020-09-04 22:45:50] "系统无法接受您的验证结果，请刷新页面后重试。"
[2020-09-04 22:45:51] "签到失败"

**Comment by nikaidou721** [comment]
站点 https://ikuuu.co

**Comment by isecret** [comment]
这个站点有验证码，脚本现在还不支持验证码哦。

**Comment by nikaidou721** [comment]
👌
