### ISSUE TITLE
微信收到的通知显示：暂不支持此消息类型，请在企业微信中查看

### ISSUE THREAD

**Issue by Bender1337** [isecret/sspanel-autocheckin#58]
企业微信里查看信息是正常的，微信里收到的消息显示：暂不支持此消息类型，请在企业微信中查看。
请问怎样设置才能在微信里正常查看信息？

**Comment by isecret** [comment]
https://github.com/isecret/sspanel-autocheckin/blob/b29d6a31265f2c4b42b59df02840a169a6aca8ed/ssp-autocheckin.sh#L214-L220

或许和 markdown 渲染有关系，你可以尝试修改为 `text` 模式试试。

**Comment by isecret** [comment]
如果没问题的话告知我一下或者提交一个合并请求，这边格式已经打算放弃 markdown 格式了。

**Comment by Bender1337** [comment]
> 如果没问题的话告知我一下或者提交一个合并请求，这边格式已经打算放弃 markdown 格式了。

修改后显示正常。谢谢
