### ISSUE TITLE
这两个网站配置均正确，但是登入失败，server酱也不对劲

### ISSUE THREAD

**Issue by ldsoy** [isecret/sspanel-autocheckin#60]
![image](https://user-images.githubusercontent.com/67219859/120026701-0b400500-c025-11eb-8ff1-bd3917f37b71.png)
https://xjieshop.top/
https://xxft.cc/
1. 这两个网站，账户密码都是正确的，但是提示登入失败
2. server酱提示微信推送成功，但是微信并没有收到推送

**Comment by ldsoy** [comment]
搞了一个晚上，登入失败的原因应该是密码里面有特殊符号，靠，改成纯数字的密码就ok了

**Comment by isecret** [comment]
好像确实不支持特殊符号，算是个 bug 吧。
