### ISSUE TITLE
解析失败

### ISSUE THREAD

**Issue by changero** [isecret/sspanel-autocheckin#7]
```bash
parse error: Invalid numeric literal at line 1, column 10
[2020-09-25 23:19:17] "登录失败"
[2020-09-25 23:19:18] "签到失败"
```

**Comment by changero** [comment]
站点：https://www.baipiaoyun.xyz/

**Comment by isecret** [comment]
我这边看见你的任务似乎已经成功了哦，什么原因造成的呢？

**Comment by changero** [comment]
貌似跟网站地址有关系，换其他网址不会出现这个报错。有点像是jq抛出来的错误，具体不太懂了，麻烦大佬帮忙看下
😄

**Comment by changero** [comment]
> 我这边看见你的任务似乎已经成功了哦，什么原因造成的呢？

actions里面那一个是成功的，我尝试在vps上执行出现的错误

**Comment by isecret** [comment]
配置中 `DOMAIN `  尾部不应该有 `/` 哦，你使用 curl 命令或者 postman 试试呢，大概率是配置问题哦。

**Comment by changero** [comment]
> 配置中 `DOMAIN` 尾部不应该有 `/` 哦，你使用 curl 命令或者 postman 试试呢，大概率是配置问题哦。

这个网站登录的时候会有cookie校验，调login的返回如图所示：
![image](https://user-images.githubusercontent.com/17746517/94431498-f37b5d00-01c7-11eb-862d-45ed9f03fd2d.png)
应该是被重定向了。

不搞了
