### ISSUE TITLE
https://ggme.xyz/auth/login 这个机场无法签到

### ISSUE THREAD

**Issue by YNight-FZQ** [isecret/sspanel-autocheckin#72]
我尝试使用各种密码全都提示：登陆失败，请检查配置
我使用的密码有：纯数字密码；纯小写字母密码；纯大写字母密码；大小写、数字和字符组合的密码
这四种类型的密码都是无法登陆的；希望大神能告诉我这个应该如何解决。

**Comment by isecret** [comment]
看一下是否有开启 cf 5 秒盾？

**Comment by YNight-FZQ** [comment]
不好意思哈，我不太清楚什么是5秒盾，这个机场打开登陆界面的时候会弹出来一个提示框，然后在登陆的时候需要做一个拖动滑块完成拼图的验证

**Comment by isecret** [comment]
有验证码的不支持自动签到。

**Comment by YNight-FZQ** [comment]
好的，谢谢你啦
